# Generated by Django 4.2.6 on 2023-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='matric_number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
