# Generated by Django 4.2.6 on 2023-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_students_matric_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='academic_background',
            field=models.CharField(default='', max_length=50),
        ),
    ]
